### ISSUE TITLE
eval_conflict_error: object keys must be unique.

### ISSUE THREAD

**Issue by agadelshin** [fugue/regula#49]
Hi there!
Wanted to try your solution for OPA checks but see the error.

```
{
  "errors": [
    {
      "message": "object keys must be unique",
      "code": "eval_conflict_error",
      "location": {
        "file": "regula/lib/fugue_resource_view.rego",
        "row": 65,
        "col": 11
      }
    }
  ]
}
```

Could you please help me understand root cause of this issue.

**Comment by jaspervdj-luminal** [comment]
Hi @agadelshin!  Thanks for reporting this.

This looks a bug in our Rego code that "flattens" the resources present in the Terraform modules and resolves the variables.  Is there any chance you could share (some) of the Terraform configuration that is causing this issue?

**Comment by agadelshin** [comment]
hm, I'm not sure about sharing the code. maybe you can suggest me what part of the state should I share with you and I'll try to obfuscate it if it's possible

**Comment by andrewrdakers** [comment]
I'm also having this issue. Any guidance would be great.

**Comment by jaspervdj-luminal** [comment]
Is there any chance either of you could try this again with current `master`?  I think #50 should have fixed it but it would be nice to have confirmation.

**Comment by andrewrdakers** [comment]
That fixed the issue for me. Thank you.

**Comment by jaspervdj-luminal** [comment]
This should be fixed in `regula-v0.4.0`, so I'm closing this issue for now.  If you still run into trouble let me know @agadelshin :-)

**Comment by rosspatil** [comment]
Hi @jaspervdj-luminal ,

I am still facing the same issue even after update to `regula-0.4.0`.

`
{
  "code": "internal_error",
  "message": "error(s) occurred while evaluating query",
  "errors": [
    {
      "code": "eval_conflict_error",
      "message": "object keys must be unique",
      "location": {
        "file": "./fugue_resource_view.rego",
        "row": 65,
        "col": 11
      }
    }
  ]
}
`
